  library(corrplot)
  library(corrgram)
  library(PerformanceAnalytics)
  library(data.table)
  data<-read.csv("new1.csv")
  data$Item_Fat_Content<-as.numeric(data$Item_Fat_Content)
  data$Item_Type<-as.numeric(data$Item_Type)
  data$Outlet_Location_Type <- as.numeric(data$Outlet_Location_Type)
  data$Outlet_Type <- as.numeric(data$Outlet_Type)
  cor<-cor(data[,c(2,3,4,5,6,10,11,12)])
  corrplot(corr=cor,type="upper",order="hclust",tl.col = "black",tl.srt=45)
  chart.Correlation(cor,histogram = FALSE,pch=19)
  Test1 <- xtabs(~data$Item_Visibility+data$Item_Outlet_Sales)
  Test2  <-xtabs(~data$Item_Weight+data$Item_Outlet_Sales)
  Test3  <-xtabs(~data$Item_MRP+data$Item_Outlet_Sales)
  chisq.test(Test1)
  chisq.test(Test2)
  chisq.test(Test3)
  t.test(data$Item_MRP,data$Item_Outlet_Sales)